import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
from datetime import timedelta, date

# ==========================================
# 1. PAGE SETUP & MOCK DATA GENERATOR
# ==========================================
st.set_page_config(page_title="Insider Threat SOC", layout="wide")

@st.cache_data
def load_real_data(file_path="features/scored_features_latest.parquet"):
    """Loads the actual feature matrix generated by the DuckDB + ML pipeline."""
    try:
        # 1. Load the parquet file
        df = pd.read_parquet(file_path)
        
        # 2. Flatten the MultiIndex
        # DuckDB saved 'user' and 'activity_date' as the index. 
        # We must reset it so they become regular columns for Plotly to graph.
        df = df.reset_index()
        
        # 3. Standardize the Date Format
        # Parquet saves dates as timestamps (e.g., 2026-05-01 00:00:00). 
        # We convert it to a pure date object so the Streamlit date slider matches perfectly.
        if pd.api.types.is_datetime64_any_dtype(df['activity_date']):
            df['activity_date'] = df['activity_date'].dt.date
            
        # 4. Sort chronologically
        return df.sort_values('activity_date')
        
    except FileNotFoundError:
        # 5. Graceful Failure
        st.error(f"🚨 Critical Error: Could not find '{file_path}'.")
        st.warning("Please run the 'run_inference.py' ML script to generate the data before opening the dashboard.")
        st.stop() # This halts the script immediately so the UI doesn't throw a massive Pandas crash error

# Load the real data
df = load_real_data()


# Global Context
today = df['activity_date'].max()
latest_data = df[df['activity_date'] == today].copy()

# Header
st.title("🚨 SOC Alert Triage & Investigation")
st.markdown("---")

# ==========================================
# PHASE 1: THE RANKED TRIAGE LIST (Macro-Urgency)
# ==========================================
st.subheader("1. Active Threat Queue (Action Required)")
st.write("Users ranked by aggregate risk and telemetry tampering indicators.")

# Sort by highest risk and data quality tampering
triage_queue = latest_data.sort_values(
    by=['risk_score', 'data_quality_risk'], 
    ascending=[False, False]
)

# Top KPIs
col1, col2, col3, col4 = st.columns(4)
critical_count = len(triage_queue[triage_queue['risk_score'] > 0.75])
tamper_count = len(triage_queue[triage_queue['data_quality_risk'] == 1])

col1.metric("Active Sessions", len(triage_queue))
col2.metric("Critical Threats (Risk > 0.75)", critical_count, delta=critical_count, delta_color="inverse")
col3.metric("Data Tampering Alerts", tamper_count, delta=tamper_count, delta_color="inverse")
col4.metric("Highest Active Score", f"{triage_queue['risk_score'].max():.2f}")

# Clean up the dataframe for the analyst's eyes
display_cols = ['user', 'risk_score', 'data_quality_risk', 'total_events']
st.dataframe(
    triage_queue[display_cols].style.background_gradient(subset=['risk_score'], cmap='Reds'),
    use_container_width=True,
    hide_index=True
)

st.markdown("---")

# ==========================================
# PHASE 2: SIDE-BY-SIDE DEEP DIVE (Micro-Context)
# ==========================================
st.subheader("2. User Investigation Deep Dive")
st.write("Select a user from the triage queue to analyze their behavioral trajectory and ML feature attributions.")

# Default to the most critical user
top_threat_user = triage_queue.iloc[0]['user']
selected_user = st.selectbox("Investigating User:", triage_queue['user'].unique(), index=0)

# Filter data for the selected user
user_history = df[df['user'] == selected_user]
user_today = user_history[user_history['activity_date'] == today].iloc[0]

# Split into two columns as requested
chart_col1, chart_col2 = st.columns(2)

with chart_col1:
    st.markdown("**Why did the model flag this? (SHAP Analysis)**")
    
    # Format SHAP data for Plotly
    shap_data = pd.DataFrame({
        'Feature': ['Off-Hours Activity', 'Active Orphan Sessions', 'Failed Logins'],
        'Contribution': [
            user_today['shap_off_hours'], 
            user_today['shap_orphans'], 
            user_today['shap_failed_logins']
        ]
    })
    
    # Conditional coloring: Red for risk-increasing, Gray for neutral/safe
    shap_data['Color'] = np.where(shap_data['Contribution'] > 0, 'Crimson', 'LightGray')
    
    fig_shap = px.bar(
        shap_data, x='Contribution', y='Feature', orientation='h',
        title=f"Feature Impact on Risk Score ({today})",
        color='Color', color_discrete_map="identity"
    )
    fig_shap.update_layout(xaxis_title="Impact Magnitude", yaxis_title="")
    st.plotly_chart(fig_shap, use_container_width=True)

with chart_col2:
    st.markdown("**How is this unfolding? (14-Day Trajectory)**")
    
    fig_line = px.line(
        user_history, x='activity_date', y='risk_score',
        markers=True, title=f"Risk Trend: {selected_user}"
    )
    fig_line.add_hline(y=0.75, line_dash="dash", line_color="red", annotation_text="Critical Threshold")
    # Dynamically scale Y axis so small bumps don't look massive
    fig_line.update_layout(yaxis_range=[0, 1.05], xaxis_title="", yaxis_title="ML Risk Score") 
    st.plotly_chart(fig_line, use_container_width=True)

st.markdown("---")

# ==========================================
# PHASE 3: FLEET-WIDE HEATMAP (Blast Radius)
# ==========================================
st.subheader("3. Systemic Threat Analysis (Blast Radius)")
st.write("Scan for coordinated attacks, lateral movement campaigns, or systemic IT misconfigurations.")

fig_heat = px.density_heatmap(
    df, x='activity_date', y='user', z='risk_score', 
    histfunc='max', color_continuous_scale='Reds',
    title="14-Day Fleet Anomaly Heatmap"
)
fig_heat.update_layout(height=500, margin=dict(l=0, r=0, t=40, b=0))
st.plotly_chart(fig_heat, use_container_width=True)